version: '3.8'

services:
# Larvel container
  app:
    build: .
    container_name: mypallet_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - mypallet
    command: php artisan serve --host=0.0.0.0 --port=8000

# Postgres container
  db:
    image: postgres:15
    container_name: mypallet_postgres
    environment:
      POSTGRES_DB: mypallet
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - mypallet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  mypallet:

volumes:
  pgdata: