version: '3.8'

services:
  app:
    build: .
    image: mypallet_app:latest
    container_name: mypallet_app
    restart: always
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - mypallet
  
  web:
    image: nginx:alpine
    container_name: mypallet_nginx
    restart: always
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - mypallet

  db:
    image: postgres:15
    container_name: mypallet_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: mypallet
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - mypallet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  mypallet:
    driver: bridge 

volumes:
  pgdata: